# This is a basic workflow to help you get started with Actions

name: conchayoro-pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: executa comando
run: echo "Configuração inicial do pipeline"
