# This is a basic workflow to help you get started with Actions

name: conchayoro-pipeline
on:
   worklow_dispatch
 
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: executa comando
    run: echo "Configuração inicial do pipeline"
