# This is a basic workflow to help you get started with Actions


name: steps examples
on:
  push:
      branches: [ "main" ]
jobs:
  marketplace:
     runs-on: ubuntu-latest
     steps:
     - name: executa comando
       run: echo "Steps examples"
